<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpMmYLC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpMmYLC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpMmYLC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpMmYLC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXpMmYLC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XpMmYLC',
    'container.build_id' => 'f203fb88',
    'container.build_time' => 1646484320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpMmYLC');
